POST https://localhost:5001/api/usuario/criar
Content-Type: application/json

{
    "Nome" : "a",
    "Login" : "Jos",
    "Senha" : "askdjh"
}

###

GET https://localhost:5001/api/usuario/listar

###
GET https://localhost:5001/api/usuario/getbyid/1

###

GET https://localhost:5001/api/usuario/login
Content-Type: application/json

{
    "Login" : "ioioioio@hotmail.com",
    "Senha" : "ioioioio2"
}